### ISSUE TITLE
浏览器和postman能调通api但是Alamofire不能正常获取接口的数据

### ISSUE THREAD

**Issue by MartinMugiMai** [BlankerL/DXY-2019-nCoV-Crawler#126] opened 2020-12-15 09:34 UTC
2020-12-15 17:30:56.380663+0800 iYDa[6904:40645799] Task <3E23D370-21AC-40AA-B5B2-D68262C4FE27>.<2> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600002e48f60 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3E23D370-21AC-40AA-B5B2-D68262C4FE27>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3E23D370-21AC-40AA-B5B2-D68262C4FE27>.<2>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://lab.isaaclin.cn/nCoV/api/area?latest=1&province=%E6%B1%9F%E9%97%A8, NSErrorFailingURLKey=https://lab.isaaclin.cn/nCoV/api/area?latest=1&province=%E6%B1%9F%E9%97%A8, _kCFStreamErrorDomainKey=4}
2020-12-15 17:31:09.853527+0800 iYDa[6904:40644417] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by BlankerL** [comment] 2020-12-16 17:23
Duplicate of #124

**Closed as completed by BlankerL** 2020-12-16 17:23 UTC
Labels: duplicate
