### ISSUE TITLE
province_suspectedCount的问题

### ISSUE THREAD

**Issue by yanghai6** [BlankerL/DXY-2019-nCoV-Crawler#59] opened 2020-02-13 22:42 UTC
province_suspectedCount是疑似病例吗？为什么最近的数据province_suspectedCount都是0诶？

provinceName,cityName,province_confirmedCount,province_suspectedCount,province_curedCount,province_deadCount,city_confirmedCount,city_suspectedCount,city_curedCount,city_deadCount,updateTime
甘肃省,兰州,90,0,39,2,35,0,14,2,2020-02-13 23:51:34.768
甘肃省,平凉,90,0,39,2,9,0,1,0,2020-02-13 23:51:34.768
甘肃省,甘南,90,0,39,2,8,0,1,0,2020-02-13 23:51:34.768
甘肃省,天水,90,0,39,2,12,0,6,0,2020-02-13 23:51:34.768
甘肃省,定西,90,0,39,2,9,0,3,0,2020-02-13 23:51:34.768

**Comment by BlankerL** [comment] 2020-02-14 09:18
Duplicate of #12

**Closed as completed by BlankerL** 2020-02-14 09:18 UTC
Labels: duplicate
