### ISSUE TITLE
似乎所有的省份里面的疑似人数都是0

### ISSUE THREAD

**Issue by langyuxiansheng** [BlankerL/DXY-2019-nCoV-Crawler#45] opened 2020-02-06 12:53 UTC
四川
![image](https://user-images.githubusercontent.com/29669030/73938642-a4c04080-4922-11ea-9be9-341c946db982.png)
湖北
![image](https://user-images.githubusercontent.com/29669030/73938674-b6094d00-4922-11ea-880c-6b8b6d5772a3.png)

**Comment by BlankerL** [comment] 2020-02-06 18:28
Duplicate of #12

**Closed as completed by BlankerL** 2020-02-06 18:28 UTC
Labels: duplicate
